services:
  mysql-db:
    image: mysql:8.4 
    container_name: mysql-artesanos
    restart: always
    environment:
      MYSQL_DATABASE: artesanos
      MYSQL_ROOT_PASSWORD: masterpizza
      TZ: America/Bogota
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - artesanos-net

  backend:
    build: ./sistema_pedidos
    container_name: backend-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/artesanos?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=masterpizza
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=America/Bogota
    networks:
      - artesanos-net

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_API_URL=http://172.27.25.26:8080
    container_name: frontend-pedidos
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - artesanos-net

volumes:
  db_data:

networks:
  artesanos-net:
    driver: bridge